apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-xefw
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0046-tenant/tkrw-pr712-0075-0046-app/devfile-sample-xefw@sha256:e1626d196f9eb3922ea141ffaa48a888ab8986e79604042fe171077ff06d83f6
        name: my-nodejs
        resources: {}
status: {}
