apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-xefw
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-xefw
    app.kubernetes.io/part-of: tkrw-pr712-0075-0046-app
  name: devfile-sample-xefw
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-xefw
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-xefw
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0046-tenant/tkrw-pr712-0075-0046-app/devfile-sample-xefw@sha256:e1626d196f9eb3922ea141ffaa48a888ab8986e79604042fe171077ff06d83f6
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
